//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : 回复.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class 回复 {
	public int 回复ID;
	public String 回复内容;
	public Date 回复时间;
	public int 回复评论ID;
	public String 回复人;
	public Boolean 添加回复() {
	
	}
	
	public Boolean 删除回复() {
	
	}
	
	public int[] 查看回复() {
	
	}
}
