//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : 好友.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class 好友 extends 注册会员 {
	public String 好友名;
	public String 查看好友信息() {
	
	}
	
	public Boolean 修改好友信息() {
	
	}
}
