//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : 心情.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class 心情 {
	public int 心情ID;
	public String 心情内容;
	public Date 心情时间;
	public int 评论ID;
	public Boolean 添加心情() {
	
	}
	
	public Boolean 删除心情() {
	
	}
	
	public int[] 查看心情() {
	
	}
	
	public Boolean 添加评论() {
	
	}
	
	public Boolean 删除评论() {
	
	}
	
	public Boolean 回复评论() {
	
	}
}
