//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : 文章类别.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class 文章类别 {
	public int 分组id;
	public String 类别名称;
	public int 文章数;
	public Boolean 添加分组() {
	
	}
	
	public Boolean 修改分组() {
	
	}
	
	public Boolean 删除分组() {
	
	}
	
	public int[] 查看分组() {
	
	}
}
