//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : 文章.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class 文章 {
	public int 题目ID;
	public String 题目;
	public String 内容;
	public Date 时间;
	public int 评论数;
	public int 浏览次数;
	public String 文章分类;
	public int 评论ID;
	public Boolean 添加文章() {
	
	}
	
	public Boolean 删除文章() {
	
	}
	
	public Boolean 修改文章() {
	
	}
	
	public int[] 查看文章() {
	
	}
	
	public Boolean 添加评论() {
	
	}
	
	public Boolean 删除评论() {
	
	}
	
	public Boolean 添加评论回复() {
	
	}
}
