//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : 注册会员.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class 注册会员 {
	public String 会员名称;
	public String 密码;
	public Boolean 添加会员() {
	
	}
	
	public Boolean 修改会员() {
	
	}
}
