//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : 照片.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class 照片 {
	public int 照片ID;
	public Url 照片地址;
	public String 照片相册;
	public int 相册ID;
	public int 评论ID;
	public Boolean 添加相片() {
	
	}
	
	public Boolean 删除相片() {
	
	}
	
	public int[] 查找相片() {
	
	}
	
	public Boolean 添加评论() {
	
	}
	
	public Boolean 删除评论() {
	
	}
	
	public Boolean 回复评论() {
	
	}
}
