//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : 留言板回复.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class 留言板回复 {
	public int 回复ID;
	public Date 回复时间;
	public String 回复内容;
	public String 回复人;
	public Boolean 添加留言板回复() {
	
	}
	
	public int[] 查看回复() {
	
	}
}
