//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : ÁôÑÔ°å.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class ÁôÑÔ°å {
	public String ÁôÑÔ×÷Õß;
	public Date ÁôÑÔÊ±¼ä;
	public int ÁôÑÔID;
	public int »Ø¸´ID;
	public Boolean Ìí¼ÓÁôÑÔ() {
	
	}
	
	public Boolean É¾³ıÁôÑÔ() {
	
	}
	
	public int[] ²é¿´ÁôÑÔ() {
	
	}
	
	public Boolean Ìí¼Ó»Ø¸´() {
	
	}
}
