//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : 相册.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class 相册 {
	public int 相册ID;
	public String 相册名称;
	public int 相册数量;
	public Boolean 添加相册() {
	
	}
	
	public Boolean 删除相册() {
	
	}
	
	public Boolean 修改相册() {
	
	}
	
	public int[] 查看相册() {
	
	}
}
