//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @blog
//  @ File Name : 评论.java
//  @ Date : 2014/11/21
//  @ Author : @judyge
//
//




public class 评论 {
	public Object 评论ID;
	public Object 评论会员;
	public Object 评论时间;
	public Object 评论内容;
	public Object 回复id;
	public Boolean 添加评论() {
	
	}
	
	public Boolean 删除评论() {
	
	}
	
	public int[] 查看评论() {
	
	}
	
	public Boolean 回复评论() {
	
	}
}
